version: '3.8'
services:
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.test
    ports:
      - 8000:8000
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.test
    ports:
      - 5000:5000
